version: '3'
services:

  #PHP Service
  app:
    container_name: todo_app
    build:
      context: ./docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
            - ./:/var/www
    restart: unless-stopped
    tty: true
    networks:
      - todo-network
  #Web Server(NGINX)
  web:
    container_name: todo_web
    build:
        context: ./docker
        dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    ports:
        - 8010:80
    networks:
      - todo-network

  #MySQL Service
  db:
    container_name: todo_db
    image: mariadb
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USERNAME: todo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: todo
    volumes:
      - ./dbdata1:/var/lib/mysql/
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - todo-network

  phpmyadmin:
    container_name: todo_pma
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=todo_db
      - PMA_USER=root
      - PMA_PASSWORD=todo
      - MAX_EXECUTION_TIME=3600
      - UPLOAD_LIMIT=512M
    networks:
      - todo-network
networks:
  todo-network:
    driver: bridge
