version: "3"

services:

  # Web server
  web:
    build: .
    container_name: todolist-web
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/html

  # Database
  db:
    image: mysql:latest
    container_name: todolist-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    volumes:
      - ./db-data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: todolist-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: todolist-db
      PMA_USER: root
      PMA_PASSWORD: root

networks:
  default:
    name: todolist-network
